import { StyleSheet } from 'react-native';

const homestyles = StyleSheet.create({
  container: {
    height:840,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  containerConfirm: {
    height:800,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  img:{
    width: 100,
    height: 150,
    right: 120,
  },
  phoneContainer: {
    marginTop: 28,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  padding: 3,
  width: 300,
  marginRight: 5,
  fontSize: 17,
  borderWidth: 1,
  borderColor: 'black',
  borderRadius: 10,
  },
  phoneContainerConfirm: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  padding: 3,
  width: 300,
  marginRight: 5,
  fontSize: 17,
  borderWidth: 1,
  borderColor: 'black',
  borderRadius: 10,
  },
  button: {
    marginTop: 30,
    width: '75%',
    padding: 30,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'green',
  },
  textInput: {
    paddingVertical: 0,
    backgroundColor: 'white',
  },
  title:{
    width: 300,
    fontSize: 65,
    fontWeight: '700',
    borderBottomColor: 'black',
    borderBottomWidth: 1,
  }, 
  title2:{
    width: 300,
    fontSize: 50,
    fontWeight: '700',
    borderBottomColor: 'black',
    borderBottomWidth: 1,
  },
  desc:{
    width: 300,
    marginBottom: 60,
    fontSize: 16,
    color: '#5c5e62',
    marginTop: 15,
    fontFamily: 'Poppins-Light',
    },
    username:{
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    padding: 3,
    width: 300,
    marginRight: 5,
    fontSize: 17,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 10,
    },
    username2:{
      justifyContent: 'center',
      alignItems: 'center',
      flexDirection: 'row',
    padding: 3,
    width: 300,
    marginRight: 5,
    fontSize: 17,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 10,
    bottom: 50,
    },
    email: {
    marginTop: 28,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  padding: 3,
  width: 300,
  marginRight: 5,
  fontSize: 17,
  borderWidth: 1,
  borderColor: 'black',
  borderRadius: 10,
    },

    password:{
    marginTop: 30,
    height: 48,
    padding: 3,
    width: 300,
    marginRight: 5,
    fontSize: 17,
    borderWidth: 1,
    borderColor: 'black',
    borderRadius: 10,
    color: 'black'
    },

    operate:{
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 150,
    flex: 1,
    flexDirection: "column",
    },
    operate2:{
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 110,
      flex: 1,
      flexDirection: "column",
      bottom: 50
      },
    toSignup:{
    padding: 4,
    marginTop: 10,
    color: 'black',
    height: 30,
    }, 
    toLogin:{
      top: 10,
      padding: 4,
      marginTop: 5,
      color: 'black',
      marginBottom: 8,
      height: 30
      }, 
    button: {
      width: 250,
      height: 55,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 15,
  },
  button2: {
    width: 250,
    height: 55,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 120,
},

confirmBtn:{
  width: 250,
  height: 55,
  justifyContent: 'center',
  alignItems: 'center',
  top: 45,  
},
checkbox:{
  top: 20,
flexDirection: 'row',
width: "80%",
alignItems: 'center',
justifyContent: 'space-between',
marginBottom: 70
}
});

export default homestyles;